export const games = [
  {
    id: "1",
    slug: "rooster-rumble",
    title: "Rooster Rumble",
    title1: "ROOSTER",
    title2: "RUMBLE",
    genre: "STRATEGIC GLADIATOR • PVP FIGHTING",
    subtitle: "Train Your Rooster. Rule the Rumble.",
    description:
      "Raise your rooster from a humble chick, train it into a fierce fighter, and battle your way to become the ultimate Rumble Champion.",
    missionDescription:
      "Raise your rooster from a humble chick, train it into a fierce fighter, and battle your way to become the ultimate Rumble Champion. This PvP mobile game delivers fast-paced, strategic gladiator action with deep gameplay mechanics designed for competitive play.",
    image: "/rooster-rumble/cover.jpeg",
    images: ["/banner/rooster.jpeg"],
    inDevelopment: true,
    about: {
      title1: "ROOSTER",
      title1Red: "RUMBLE",
      descriptions: [
        "Rooster Rumble is a free-to-play mobile game where you adopt a rooster, train it from scratch, and build the ultimate fighting champion.",
        "Customize your fighter, master unique battle styles, collect rare roosters, and compete in intense 1v1 PvP bouts and multiplayer tournaments. The deeper you go, the fiercer the competition - do you have what it takes to rule the Rumble?",
      ],
      tags: ["FREE TO PLAY", "IN-APP PURCHASES", "IOS & ANDROID"],
      footer: "FOR GAMERS WHO LOVE STRATEGY, PROGRESSION & COMPETITION",
      images: ["/rooster-rumble/char-2.png", "/rooster-rumble/char-1.png"],
      flipSecond: true,
    },
    video: "/videos/rooster-rumble.mp4",
    rating: "5.0",
    platforms: ["iOS", "Android"],
    engine: "UNITY 6.3",
    region: "GLOBAL RELEASE",
    buttonTitle: "LEARN MORE",
    href: true,
  },
  {
    id: "2",
    slug: "rot-in-hell",
    title: "Rot in Hell",
    title1: "ROT IN",
    title2: "HELL",
    genre: "SOUL-LIKE SURVIVAL • HARDCORE ACTION",
    subtitle: "Death is only the beginning.",
    description:
      "Descend into a nightmarish underworld in this uncompromising soul-like survival saga. Battle death itself to live again.",
    missionDescription:
      "Descend into a nightmarish underworld in this intense soul-like survival experience. Battle unforgiving enemies, navigate treacherous environments, and master precise combat to stay alive. Every encounter tests your skill, strategy, and perseverance, creating a challenging yet rewarding journey for those brave enough to face it.",
    image: "/rot-in-hell/cover.png",
    images: [
      "/banner/1.jpg",
      "/banner/2.jpg",
      "/banner/3.jpg",
      "/banner/4.jpg",
      "/banner/5.jpg",
      "/banner/6.jpg",
    ],
    inDevelopment: true,
    about: {
      title1: "ROT",
      title1Red: "IN HELL",
      descriptions: [
        "Rot In Hell is an action adventure game that draws inspiration from souls like genre. Rot in Hell offers players a harrowing journey through a twisted world as Damien, the tormented character, challenges them to confront their inner demons while battling external forces of darkness.",
        "Twisted Hell is a dark, atmospheric game that pulls players into a haunting world filled with eerie landscapes and unsettling visuals. You play as Damien, a tormented protagonist whose painful past and inner demons slowly unfold as the story progresses. The narrative is linear and cinematic, keeping the experience focused while building emotional depth and psychological tension.",
        "The gameplay features fast-paced, Souls-like combat with challenging enemies and strategic timing. As players advance, they unlock abilities, weapons, and memories that reveal Damien’s story. With immersive visuals, intense sound design, and twist-filled endings, the game encourages replayability by making players revisit hidden clues and missed story elements.",
      ],
      images: ["/images/damien.png"],
    },
    video: "/videos/rot-in-hell.mp4",
    rating: "4.9",
    platforms: ["PC", "PS5", "XBOX"],
    engine: "Unity 6.3",
    region: "GLOBAL RELEASE",
    buttonTitle: "LEARN MORE",
    href: true,
    steamWidgetId: "2701500",
  },
];
